# Generated by Django 3.2 on 2021-05-05 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='evidencijagospodarstva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('katastar', models.CharField(max_length=120)),
                ('naselje', models.CharField(max_length=50)),
                ('povrsina', models.CharField(max_length=50)),
                ('naziv_gosp', models.CharField(max_length=30)),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='podaci_radnje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrstaradnje', models.CharField(max_length=120)),
                ('katcest', models.CharField(max_length=120)),
                ('datum', models.DateField()),
                ('evidencijagospodarstva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOliveBackend.evidencijagospodarstva')),
            ],
        ),
        migrations.CreateModel(
            name='spricanje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazivtek', models.CharField(max_length=120)),
                ('kolicina', models.DecimalField(decimal_places=2, max_digits=10)),
                ('katcest', models.CharField(max_length=120)),
                ('datums', models.DateField()),
                ('podaci_radnje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOliveBackend.podaci_radnje')),
            ],
        ),
        migrations.CreateModel(
            name='prihranjivanje',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nazivprihrane', models.CharField(max_length=120)),
                ('kolicinap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('katcest', models.CharField(max_length=120)),
                ('datump', models.DateField()),
                ('podaci_radnje_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOliveBackend.podaci_radnje')),
            ],
        ),
        migrations.CreateModel(
            name='berba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrstamaslina', models.CharField(max_length=120)),
                ('datumb', models.DateField()),
                ('katcest', models.CharField(max_length=120)),
                ('kolicinaubrano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doprinosulja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evidencijagospodarstva_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EOliveBackend.evidencijagospodarstva')),
            ],
        ),
    ]
