# Generated by Django 3.2 on 2021-09-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencijagospodarstva',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv_gosp', models.CharField(max_length=30)),
                ('katastar', models.CharField(max_length=120)),
                ('povrsina', models.CharField(max_length=50)),
                ('datum', models.DateField()),
                ('opis_radnje', models.CharField(max_length=50)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Berba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrstamaslina', models.CharField(max_length=120)),
                ('datumb', models.DateField()),
                ('katcest', models.CharField(max_length=120)),
                ('kolicinaubrano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doprinosulja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
